SELECT A.USER_ID
      ,B.USER_NM
      ,C.IMG_URL
      ,SUM(IF(ORDER_STATUS = 'COMPLETE' , 1, 0)) AS COMPLETE_CNT
      ,SUM(IF(ORDER_STATUS = 'SHIPPING' , 1, 0)) AS SHIPPING_CNT
      ,SUM(IF(ORDER_STATUS = 'READY' , 1, 0)) AS READY_CNT
FROM PRODUCT_ORDER A
JOIN USER B
  ON A.USER_ID = B.USER_ID
LEFT OUTER JOIN USER_PROFILE_IMG C
ON A.USER_ID = C.USER_ID
WHERE A.USER_ID = 'imstillhungry@wadiz.kr'
GROUP BY USER_ID
        ,USER_NM
        ,IMG_URL
;